# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20151029_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
