# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20151220_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.TextField(),
        ),
    ]
