# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20151220_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=999),
        ),
    ]
